GET http://localhost:4000/
###
GET http://localhost:4000/ads
####
POST http://localhost:4000/ads
Content-Type: application/json

{
  "title": "test",
  "description": "hello spyro",
  "owner": "Raphael",
  "price": 42,
  "createdAt": "now",
  "picture": "https://imgur.com",
  "location": "Toulouse"
}