GET http://localhost:3000

###
GET http://localhost:3000/categories

###
GET http://localhost:3000/ads

###
GET http://localhost:3000/ads?categoryId=2

###
GET http://localhost:3000/ads/2

###
DELETE http://localhost:3000/ads/2

###
POST http://localhost:3000/ads
Content-Type: application/json

{
		"title":"Toto",
		"description":"Lorem ipsum",
		"owner":"Loic",
		"price":42,
		"createdAt":"maintenant",
		"picture":"https://imgur.com",
		"location":"Lille",
		"categoryId":2
}