GET http://localhost:4000

###
GET http://localhost:4000/categories

###
GET http://localhost:4000/ads

###
GET http://localhost:4000/ads?categoryId=2

###
GET http://localhost:4000/ads/2

###
DELETE http://localhost:4000/ads/2

###
POST http://localhost:4000/ads
Content-Type: application/json

{
		"title":"Hello spyro",
		"description":"un petit dragon",
		"owner":"gnasty gnorc",
		"price":1000,
		"createdAt":"maintenant",
		"picture":"https://imgur.com",
		"location":"Monde des ouvriers magiques",
		"categoryId":2
}